#ifndef PORTS_H
#define PORTS_H

#define PORT_PING 1
#define PORT_BEAM 2
#define PORT_FENCE 3
#define PORT_RPC_SERVER_PING 4
#define PORT_RPC_CLIENT_PING 5
#define PORT_RPC_SERVER_BEAM 6
#define PORT_RPC_CLIENT_BEAM 7
#define PORT_RPC_SERVER_FENCE 8
#define PORT_RPC_CLIENT_FENCE 9
#define PORT_RPC_SERVER_RCMD 10
#define PORT_RPC_CLIENT_RCMD 11
#define PORT_RPC_SERVER_IRTOP 12
#define PORT_RPC_CLIENT_IRTOP 13
#define PORT_RPC_SERVER_IRTOP_PROBE 14
#define PORT_RPC_CLIENT_IRTOP_PROBE 15
#define PORT_IRTOP 16
#define PORT_RPC_SERVER_COMPASS 17
#define PORT_RPC_CLIENT_COMPASS 18

#endif
